# Generated by Django 5.0.7 on 2024-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draw_date", models.DateTimeField(verbose_name="date published")),
                ("draw_night", models.CharField(max_length=2)),
                ("pos1", models.CharField(max_length=2)),
                ("pos2", models.CharField(max_length=2)),
                ("pos3", models.CharField(max_length=2)),
                ("pos4", models.CharField(max_length=2)),
                ("pos5", models.CharField(max_length=2)),
                ("pwrb", models.CharField(max_length=2)),
                ("mega", models.CharField(max_length=2)),
                ("Station", models.CharField(max_length=20)),
            ],
        ),
    ]
