# Generated by Django 5.0.7 on 2024-07-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="Mx",
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="drawing",
            name="draw_date",
            field=models.CharField(max_length=20),
        ),
    ]
