# Generated by Django 5.0.7 on 2024-07-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0002_drawing_mx_alter_drawing_draw_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="Barometer",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="Dewpoint",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="Heat_Index",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="Hygrometer",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="Thermometer",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
