# Generated by Django 5.0.7 on 2024-07-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0003_drawing_barometer_drawing_dewpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="CloudCover",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="MoonPhase",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="Percipitation",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="WindDirection",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="WindSpeed",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
