# Generated by Django 5.0.7 on 2024-07-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0005_remove_drawing_id_alter_drawing_draw_date"),
    ]

    operations = [
#        migrations.AddField(
#            model_name="drawing",
#            name="id",
#            field=models.BigAutoField(
#                auto_created=True,
#                default=1,
#                primary_key=False,
#                serialize=False,
#                verbose_name="ID",
#            ),
#            preserve_default=False,
#        ),
#        migrations.AlterField(
#            model_name="drawing",
#            name="draw_date",
#            field=models.CharField(max_length=20),
#        ),
    ]
