# Generated by Django 5.0.7 on 2024-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0006_drawing_id_alter_drawing_draw_date"),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name="drawing",
#            name="id",
#        ),
#        migrations.AlterField(
#            model_name="drawing",
#            name="draw_date",
#            field=models.CharField(max_length=20, primary_key=True, serialize=False),
#        ),
    ]
