# Generated by Django 5.0.7 on 2024-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0008_alter_drawing_draw_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="draw_date",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
