# Generated by Django 5.0.7 on 2024-07-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draws", "0009_alter_drawing_draw_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherDrawing",
            fields=[
                (
                    "draw_date",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("draw_night", models.CharField(max_length=2)),
                ("pos1", models.CharField(max_length=2)),
                ("pos2", models.CharField(max_length=2)),
                ("pos3", models.CharField(max_length=2)),
                ("pos4", models.CharField(max_length=2)),
                ("pos5", models.CharField(max_length=2)),
                ("pwrb", models.CharField(max_length=2)),
                ("mega", models.CharField(max_length=2)),
                ("Mx", models.CharField(max_length=2)),
                ("Barometer", models.FloatField()),
                ("Dewpoint", models.FloatField()),
                ("Heat_Index", models.FloatField()),
                ("Hygrometer", models.FloatField()),
                ("Thermometer", models.FloatField()),
                ("Percipitation", models.FloatField()),
                ("WindDirection", models.FloatField()),
                ("CloudCover", models.FloatField()),
                ("WindSpeed", models.FloatField()),
                ("MoonPhase", models.FloatField()),
                ("Station", models.CharField(max_length=20)),
            ],
        ),
    ]
